In [8]:
import numpy as np
import sklearn.model_selection
from sklearn import datasets
import sklearn.metrics
import shutil
import autosklearn.classification
import autosklearn.regression
import pickle
import sys

import warnings
warnings.filterwarnings("ignore")

In [66]:
# Inputs: X, y, regression or classification
class base_multi_automl:
    def __init__(self, model_type):
        self.model_type = model_type
        pass
    
    # X and y are NP matrices, assumes groups is an np vector with indicators starting from 0
    def fit(self, X, y, groups)
        # Split X into a list of Xs based on group assignments
        
                        
        # Train each group on automl
                
        # Retrive a list of models bas ed on automl
        
        # Create a new dataset based on training each instance's groups for each model and supplying a prediction
        
        # Train this new dataset to get the weights for each model
        
        # Return a the list of models and the weights of each model
        
    def test(self, X, y, block_presence)
        # X and y should be in same structure as before
        # Block presence indicates which blocks are missing or not
        
        # Split X into the data groups
        # Train each group on the saved automl models/weights
        # Ensemble them with the group model normalized over present blocks        
        
        
        

SyntaxError: invalid syntax (<ipython-input-66-9323219b5582>, line 8)

In [3]:
diabetes = datasets.load_diabetes()
X = diabetes.data
y = diabetes.target
groups = np.array([0, 0, 0, 1, 0, 1, 0, 2, 1, 2])

In [4]:
m, d = np.shape(X_train)
total_group_num = np.size(np.unique(groups))

In [18]:
# Group Splitter
X_sorted = np.zeros((m, d))
group_counts = [0] * total_group_num
col_num = 0

# Sort the Xs by the groups and derive counts for each group
for group_num in range(total_group_num):
    for feature in range(d):        
        if group_num == groups[feature]:
            X_sorted[:, col_num] = X[:, feature]
            col_num += 1
            group_counts[group_num] += 1

# Pass in sorted X data and retrieve a list of blocks
def create_groups(X_data):
    # Create a list of the groups
    X_groups = [np.empty(1) for i in range(total_group_num)]
    for group_num in range(total_group_num):
        for feature in range(d):        
            if group_num == groups[feature]:
                if np.size(X_groups[group_num]) == 1:
                    X_groups[group_num] = np.asmatrix(X_data[:, feature]).T                
                else:
                    X_groups[group_num] = np.hstack((X_groups[group_num], np.asmatrix(X_data[:, feature]).T))                 
    return X_groups
                
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X_sorted, y, random_state=1)
X_train_groups = create_groups(X_train)
X_test_groups = create_groups(X_train)

In [6]:
# Training Each Group on AutoML
time_cap = 60
per_limit = 15
models = [0] * total_group_num
for group_num in range(total_group_num):
    block_data = X_train_groups[group_num]
    automl_model = autosklearn.classification.AutoSklearnClassifier(
                time_left_for_this_task = time_cap,
                per_run_time_limit = per_limit)
    automl_model.fit(block_data, y)
    models[group_num] = pickle.dumps(automl_model)
    

[WARNING] [2019-03-30 08:48:03,379:EnsembleBuilder(1):c23126a636c3e2c7476a944ebbca4ad7] No models better than random - using Dummy Score!
[WARNING] [2019-03-30 08:48:03,384:EnsembleBuilder(1):c23126a636c3e2c7476a944ebbca4ad7] No models better than random - using Dummy Score!


Process pynisher function call:
Traceback (most recent call last):
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/site-packages/pynisher/limit_function_call.py", line 93, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/site-packages/autosklearn/smbo.py", line 348, in _calculate_metafeatures_encoded
    self.logger)
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/site-packages/autosklearn/smbo.py", line 119, in _calculate_metafeatures_encoded
    dataset_name=basename, dont_calculate=EXCLUDE_META_FEATURES)
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/site-packages/autosklearn/metalearning/metafeatures/metafe

[WARNING] [2019-03-30 08:48:05,391:EnsembleBuilder(1):c23126a636c3e2c7476a944ebbca4ad7] No models better than random - using Dummy Score!
[WARNING] [2019-03-30 08:48:58,715:EnsembleBuilder(1):7d404b22af7d85f3615bb09c3c265d10] No models better than random - using Dummy Score!
[WARNING] [2019-03-30 08:48:58,724:EnsembleBuilder(1):7d404b22af7d85f3615bb09c3c265d10] No models better than random - using Dummy Score!


Process pynisher function call:
Traceback (most recent call last):
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/site-packages/pynisher/limit_function_call.py", line 93, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/site-packages/autosklearn/smbo.py", line 348, in _calculate_metafeatures_encoded
    self.logger)
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/site-packages/autosklearn/smbo.py", line 119, in _calculate_metafeatures_encoded
    dataset_name=basename, dont_calculate=EXCLUDE_META_FEATURES)
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/site-packages/autosklearn/metalearning/metafeatures/metafe

[WARNING] [2019-03-30 08:49:54,047:EnsembleBuilder(1):9413812450df0080549c70d9b02b35dc] No models better than random - using Dummy Score!
[WARNING] [2019-03-30 08:49:54,053:EnsembleBuilder(1):9413812450df0080549c70d9b02b35dc] No models better than random - using Dummy Score!


Process pynisher function call:
Traceback (most recent call last):
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/site-packages/pynisher/limit_function_call.py", line 93, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/site-packages/autosklearn/smbo.py", line 348, in _calculate_metafeatures_encoded
    self.logger)
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/site-packages/autosklearn/smbo.py", line 119, in _calculate_metafeatures_encoded
    dataset_name=basename, dont_calculate=EXCLUDE_META_FEATURES)
  File "/home/jcui/.conda/envs/auto-sklearn/lib/python3.7/site-packages/autosklearn/metalearning/metafeatures/metafe

In [27]:
# Start index indicator for cumulative counts
count = 0
starts = [0] * total_group_num
for i in range(total_group_num):
    starts[i] = count
    count += group_counts[i]
starts.append(d)

In [31]:
# Create a data table for model predictions of each classifier
block_scores_X = np.empty((m, total_group_num))
for group_num in range(total_group_num):
    print('GROUP NUM ', group_num)
    group_automl_model = pickle.loads(models[group_num])
    
    start_index = starts[group_num]
    end_index = starts[group_num+1]
    block = X_test_groups[group_num]
    print("")
    print(group_instance)
    print(group_automl_model.predict(block)
    
        


[ 0.03807591  0.05068012  0.06169621 -0.0442235  -0.04340085]
[140.]

[-0.00188202 -0.04464164 -0.05147406 -0.00844872  0.07441156]
[75.]

[ 0.08529891  0.05068012  0.04445121 -0.04559945 -0.03235593]
[132.]

[-0.08906294 -0.04464164 -0.01159501  0.01219057 -0.03603757]
[181.]

[ 0.00538306 -0.04464164 -0.03638469  0.00393485  0.00814208]
[143.]

[-0.09269548 -0.04464164 -0.04069594 -0.06899065  0.04127682]
[96.]

[-0.04547248  0.05068012 -0.04716281 -0.04009564  0.00077881]
[107.]

[ 0.06350368  0.05068012 -0.00189471  0.09061988  0.02286863]
[63.]

[ 0.04170844  0.05068012  0.06169621 -0.01395254 -0.02867429]
[102.]

[-0.07090025 -0.04464164  0.03906215 -0.01257658 -0.02499266]
[261.]

[-0.09632802 -0.04464164 -0.08380842 -0.10338947 -0.01394774]
[97.]

[ 0.02717829  0.05068012  0.01750591 -0.00707277 -0.06549067]
[208.]

[ 0.01628068 -0.04464164 -0.02884001 -0.00432087  0.04495846]
[161.]

[ 0.00538306  0.05068012 -0.00189471 -0.00432087 -0.00290283]
[187.]

[ 0.04534098 -0.0446416

[161.]

[ 0.01628068 -0.04464164 -0.04716281 -0.01945635  0.03391355]
[65.]

[-0.04910502 -0.04464164  0.00457217 -0.03734373 -0.01762938]
[178.]

[ 0.06350368 -0.04464164  0.01750591  0.00806271 -0.03603757]
[155.]

[ 0.04897352  0.05068012  0.08109682  0.04383748 -0.05444576]
[261.]

[ 0.00538306  0.05068012  0.0347509   0.15253776 -0.06180903]
[83.]

[-0.00551455 -0.04464164  0.02397278 -0.03459183  0.02286863]
[110.]

[-0.00551455  0.05068012 -0.00836158 -0.03321588 -0.03603757]
[147.]

[-0.08906294 -0.04464164 -0.06117437 -0.05523112  0.04127682]
[96.]

[ 0.03444337  0.05068012 -0.00189471  0.03833367  0.0780932 ]
[98.]

[-0.05273755 -0.04464164 -0.06225218 -0.00569682  0.03023191]
[72.]

[ 0.0090156  -0.04464164  0.0164281   0.00943866 -0.02867429]
[225.]

[-0.06363517  0.05068012  0.09618619 -0.00294491 -0.00658447]
[233.]

[-0.09632802 -0.04464164 -0.06979687 -0.01945635  0.01550536]
[145.]

[ 0.01628068  0.05068012 -0.02129532  0.03420581  0.00077881]
[83.]

[-0.04183994  0.05

[214.]

[ 0.02354575 -0.04464164  0.01966154  0.08374012  0.06336665]
[219.]

[ 0.04897352  0.05068012  0.07462995 -0.00982468 -0.04340085]
[235.]

[ 0.03081083  0.05068012 -0.00836158  0.01494247  0.00814208]
[158.]

[-0.10359309  0.05068012 -0.02345095 -0.08687804 -0.01762938]
[60.]

[ 0.01628068  0.05068012 -0.046085   -0.03321588 -0.01026611]
[47.]

[-0.06000263  0.05068012  0.05415152 -0.04972731  0.02286863]
[170.]

[-0.02730979 -0.04464164 -0.03530688 -0.05660707  0.03023191]
[115.]

[ 0.04170844 -0.04464164 -0.03207344  0.07961226  0.05600338]
[83.]

[-0.08179786 -0.04464164 -0.0816528   0.0025589   0.07072993]
[51.]

[-0.04183994 -0.04464164  0.04768465  0.12777061 -0.02499266]
[215.]

[-0.01277963 -0.04464164  0.06061839  0.04796534 -0.01762938]
[155.]

[ 0.06713621 -0.04464164  0.05630715 -0.01395254 -0.03235593]
[257.]

[-0.05273755  0.05068012  0.09834182  0.06034892 -0.0581274 ]
[197.]

[ 0.00538306 -0.04464164  0.05954058  0.02457414 -0.04340085]
[90.]

[ 0.08166637 -0.0

[54.]

[-0.06000263  0.05068012  0.04984027 -0.01670444 -0.01762938]
[189.]

[-0.02004471 -0.04464164 -0.08488624 -0.03596778  0.04127682]
[89.]

[ 0.03807591  0.05068012  0.00564998  0.00668676 -0.02499266]
[139.]

[ 0.01628068 -0.04464164  0.02073935 -0.01395254 -0.00658447]
[243.]

[ 0.04170844 -0.04464164 -0.00728377 -0.04284755  0.05232174]
[163.]

[ 0.01991321  0.05068012  0.10480869 -0.03596778 -0.02499266]
[263.]

[-0.04910502  0.05068012 -0.02452876 -0.0469754  -0.06549067]
[58.]

[ 0.00175052  0.05068012 -0.00620595 -0.00982468 -0.03971921]
[208.]

[ 0.03444337 -0.04464164 -0.03854032  0.00943866 -0.00658447]
[181.]

[-0.04547248  0.05068012  0.13714305  0.04108558 -0.04340085]
[197.]

[-0.00914709  0.05068012  0.17055523  0.03007796 -0.02131102]
[201.]

[-0.01641217  0.05068012  0.00241654  0.02182224 -0.02499266]
[113.]

[-0.00914709 -0.04464164  0.03798434 -0.02496016 -0.04340085]
[230.]

[ 0.01991321 -0.04464164 -0.05794093 -0.00156896  0.07441156]
[72.]

[ 0.05260606  0.

[59.]

[ 0.07007254  0.02217226 -0.03324879]
[100.]

[ 0.00810087  0.01778818 -0.04118039]
[163.]

[-0.03665645 -0.02260797 -0.06648815]
[120.]

[-0.02632783 -0.03043668  0.03365681]
[52.]

[-0.05042793 -0.10433972 -0.05615757]
[61.]

[ 0.03564384 -0.05799375 -0.00060925]
[85.]

[0.01154374 0.04847673 0.03839325]
[230.]

[-0.04009932 -0.07866155 -0.05140054]
[61.]

[-0.0538708 -0.0273052  0.0366458]
[215.]

[-0.04009932 -0.01383982 -0.08238148]
[137.]

[-0.06075654  0.04346635 -0.03075121]
[120.]

[-0.04009932 -0.05987264 -0.01919705]
[61.]

[0.05974393 0.01496984 0.0423449 ]
[253.]

[-0.03321358  0.01215151  0.00027149]
[57.]

[-0.01714685  0.00839372 -0.01190068]
[59.]

[-0.04009932 -0.02417372 -0.01290794]
[146.]

[-0.00567061 -0.06143838 -0.05140054]
[160.]

[-0.01255635 -0.00914259 -0.06291295]
[48.]

[0.12515848 0.02624319 0.02671426]
[229.]

[-0.01255635  0.04878988  0.08449528]
[180.]

[-0.00222774  0.05317395 -0.00514531]
[195.]

[0.05630106 0.01716188 0.00371174]
[84.]

[-0.0

[53.]

[ 0.05974393 -0.00757685  0.0110081 ]
[214.]

[-0.01255635  0.03876913  0.06604821]
[219.]

[ 0.06662967 -0.00225332  0.03365681]
[235.]

[ 0.004658    0.02749578 -0.02952762]
[158.]

[-0.02288496 -0.06770135 -0.07814091]
[135.]

[ 0.01154374 -0.01603186 -0.0439854 ]
[47.]

[-0.01944209 -0.04891244 -0.0439854 ]
[170.]

[-0.02977071 -0.05862005 -0.04986847]
[115.]

[-0.06190417  0.05098192  0.04506617]
[181.]

[-0.04009932 -0.01853704 -0.01090444]
[53.]

[0.05974393 0.12801644 0.06389312]
[215.]

[0.05285819 0.02937467 0.0702113 ]
[195.]

[ 0.07351542 -0.03920484  0.07573759]
[257.]

[0.0872869  0.04878988 0.08449528]
[195.]

[-0.05616605  0.05286081 -0.00421986]
[90.]

[0.00810087 0.05661859 0.03486419]
[139.]

[ 0.07695829 -0.01227407  0.12005338]
[261.]

[-0.00567061 -0.01947649 -0.00330371]
[142.]

[-0.04698506 -0.01978964  0.02801651]
[84.]

[ 0.02531523 -0.02354742 -0.00514531]
[191.]

[-0.04239456  0.05286081 -0.03712835]
[72.]

[ 0.04252958  0.01293438 -0.0439854 ]
[50.]


[201.]

[0.05285819 0.0644473  0.04067226]
[244.]

[0.0287581  0.0735286  0.01556684]
[90.]

[-0.01944209 -0.00381907  0.02405258]
[116.]

[-0.08141377 -0.11279473 -0.02028875]
[131.]

[0.0436772  0.06883138 0.03546194]
[109.]

[-0.00567061 -0.06269098 -0.04542096]
[160.]

[0.0872869  0.02154596 0.06604821]
[199.]

[-0.02288496  0.04158746 -0.02595242]
[95.]

[-0.05042793  0.04534524 -0.00991896]
[164.]

[ 0.02187235 -0.04703355 -0.01495648]
[153.]

[-0.00567061  0.04471895  0.05568355]
[155.]

[-0.02977071  0.01998022 -0.05140054]
[103.]

[ 0.00810087  0.01089891 -0.04542096]
[49.]

[-0.04009932  0.00463594 -0.03845911]
[64.]

[-0.05042793 -0.04703355 -0.0611766 ]
[48.]

[ 0.05974393 -0.00256647  0.03119299]
[235.]

[-0.06764228  0.07916528 -0.01811827]
[64.]

[ 0.01728186 -0.01383982 -0.04687948]
[47.]

[0.00121513 0.01528299 0.04452837]
[225.]

[-0.08141377  0.02780893 -0.00421986]
[57.]

[-0.00259226 -0.01764613]
[180.]

[-0.03949338 -0.09220405]
[51.]

[-0.00259226 -0.02593034]
[9

KeyboardInterrupt: 

In [28]:
starts

[0, 5, 8, 10]

In [ ]:
y